'use client';
import {useEffect,useMemo,useState} from 'react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {columns,years,labels,historicalRows,historical,rates,policies,solution,cellStep,views,lessons,stepCells,checkCell,formatted,shiftFormula} from '@/lib/model.mjs';
const storageKey='cedarpack-lbo-v1';
export default function Home(){
 const [cells,setCells]=useState({}),[step,setStep]=useState(0),[view,setView]=useState('IS'),[active,setActive]=useState('B7'),[editing,setEditing]=useState(false),[data,setData]=useState(false),[checked,setChecked]=useState(false),[hint,setHint]=useState(false),[answer,setAnswer]=useState(false),[assisted,setAssisted]=useState([]),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false);
 const lesson=lessons[step],grid=views[view];
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(storageKey)||'null');if(s&&s.cells&&typeof s.cells==='object'){const clean={};for(const[k,v]of Object.entries(s.cells))if(k in solution&&typeof v==='string'&&v.length<=300)clean[k]=v;setCells(clean);if(Number.isInteger(s.step)&&s.step>=0&&s.step<12){setStep(s.step);setView(lessons[s.step].view);}setAssisted(Array.isArray(s.assisted)?s.assisted.filter(x=>typeof x==='string'&&x in solution):[]);}}catch{}setLoaded(true);},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(storageKey,JSON.stringify({cells,step,assisted}));}catch{setNotice('Browser saving is unavailable. Download your work before leaving.');}},[cells,step,assisted,loaded]);
 const errors=useMemo(()=>Object.fromEntries(Object.keys(solution).map(ref=>[ref,checkCell(cells,ref)])),[cells]);
 const completed=stepCells.map(refs=>refs.every(r=>!errors[r])),passed=completed.filter(Boolean).length,remaining=stepCells[step].filter(r=>errors[r]);
 function change(ref,value){if(!(ref in solution)||value.length>300)return;setCells(c=>({...c,[ref]:value}));setNotice('');}
 function go(i){setStep(i);setView(lessons[i].view);setData(false);setChecked(false);setHint(false);setAnswer(false);setEditing(false);setActive(stepCells[i][0]);}
 function selectRef(ref){const r=Number(ref.slice(1)),target=Object.entries(views).find(([,v])=>v.rows.includes(r));if(target)setView(target[0]);setActive(ref);setData(false);setTimeout(()=>document.getElementById('cell-'+ref)?.focus(),30);}
 function paste(e,ref){e.preventDefault();const text=e.clipboardData.getData('text/plain').replace(/\r/g,'').replace(/\n$/,''),rows=text.split('\n').map(r=>r.split('\t')),start=ref.charCodeAt(0),row=Number(ref.slice(1)),patch={};for(let y=0;y<rows.length;y++)for(let x=0;x<rows[y].length;x++){const key=String.fromCharCode(start+x)+(row+y),val=rows[y][x].trim();if(!val)continue;if(!(key in solution)||val.length>300){setNotice('Paste stopped: the block extends outside editable model cells. Copy only the stated source range.');return;}patch[key]=val;}setCells(c=>({...c,...patch}));setNotice(Object.keys(patch).length+' cells pasted. Check this step to review.');}
 function fill(){const raw=cells[active];if(!raw){setNotice('Enter a formula or value in the selected cell first.');return;}const r=Number(active.slice(1)),start=active.charCodeAt(0),patch={};for(let n=start+1;n<=73;n++){const ref=String.fromCharCode(n)+r;if(cellStep[ref]===cellStep[active])patch[ref]=raw.startsWith('=')?shiftFormula(raw,n-start):raw;}setCells(c=>({...c,...patch}));setNotice(Object.keys(patch).length?'Filled '+Object.keys(patch).length+' cells to the right.':'No matching cells to the right.');}
 async function copy(text){try{await navigator.clipboard.writeText(text);setNotice('Copied. Select the indicated cell and paste.');}catch{setNotice('Clipboard unavailable. Copy the displayed values manually.');}}
 function download(){const lines=Array.from({length:85},(_,i)=>{const r=i+1;return[r===2?'CedarPack Industries - INR crore':r===6?'Line item':labels[r]||'',...columns.map(c=>r===6?years[columns.indexOf(c)]:cells[c+r]||'')].map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',');});const a=document.createElement('a'),url=URL.createObjectURL(new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='CedarPack-my-LBO.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'read_lbo_progress',description:'Read the current lesson and remaining spreadsheet errors.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return{lesson:step+1,title:lesson.title,completedSteps:passed,remaining:stepCells[step].filter(r=>errors[r]).map(r=>({cell:r,issue:errors[r]}))};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[step,errors,passed,lesson.title]);
 return <main><header><div className="brand">LBO <span>/</span> LAB<small>CEDARPACK INDUSTRIES</small></div><div className="header-meta">Your first leveraged buyout<span>₹ crore · 120 minutes · 5-year investment</span></div><a className="download light" href="/CedarPack-Data.xlsx" download>↓ Case data · Excel</a></header>
 <div className="topline"><div><b>{String(step+1).padStart(2,'0')} / 12</b><span>{lesson.book}</span></div><div className="progress-wrap"><span>{passed} of 12 steps checked</span><Progress value={passed/12*100} aria-label="Completed lessons"/></div></div>
 <div className="workspace"><aside className="guide"><div className="eyebrow">{lesson.minutes} MINUTES · STEP {step+1}</div><h1>{lesson.title}</h1><p>{lesson.why}</p><div className="instruction"><h2>Your task</h2><p>{lesson.task}</p></div><button className="primary wide" onClick={()=>{setChecked(true);setNotice(remaining.length?'Review the highlighted feedback below.':'Every cell in this step is correct.');}}>Check this step</button>
 {checked&&<div className={'feedback '+(remaining.length?'needs-work':'correct')} role="status">{remaining.length?<><b>{remaining.length} cells to review</b><ul>{remaining.slice(0,4).map(r=><li key={r}><button onClick={()=>selectRef(r)}>{r}: {errors[r]}</button></li>)}</ul>{remaining.length>4&&<span>Showing the first four. Fix these and check again.</span>}</>:<><b>Step complete</b><p>{step===11?'You have built and reconciled the beginner LBO. Download your model and explain the base and downside returns.':'Your entries and formulas match the case. Continue when you can explain the result.'}</p></>}</div>}
 <button className="text-button" onClick={()=>setHint(!hint)}>{hint?'− Hide hint':'+ I need a hint'}</button>{hint&&<div className="hint"><p>{lesson.hint}</p><code>{lesson.example}</code><p>Select a cell, then reveal its worked formula if you are still stuck.</p><button onClick={()=>{if(cellStep[active]!==step){setNotice('Select a highlighted cell in this step first.');return;}change(active,solution[active]);setAssisted(a=>a.includes(active)?a:[...a,active]);}}>Reveal selected cell ({active})</button></div>}
 <details className="concept"><summary>Pause and explain</summary><p>{lesson.question}</p><button className="text-button" onClick={()=>setAnswer(!answer)}>{answer?'Hide explanation':'Show explanation'}</button>{answer&&<p>{lesson.answer}</p>}</details>
 <div className="step-nav"><button disabled={step===0} onClick={()=>go(step-1)}>← Back</button><button className="primary" disabled={step===11} onClick={()=>go(step+1)}>{completed[step]?'Next step →':'Continue →'}</button></div><p className="small">You may explore ahead. A step counts as complete only when every required cell checks correctly.</p>
 <details><summary>All 12 steps</summary><ol className="lesson-list">{lessons.map((s,i)=><li key={s.title}><button aria-current={i===step?'step':undefined} onClick={()=>go(i)}>{completed[i]?'✓ ':''}{s.title}</button></li>)}</ol></details></aside>
 <section className="sheet-area"><div className="sheet-top"><div><h2>{data?'Company information':grid.title}</h2><p>{data?'Invented data for a focused classroom exercise':'Years ended 31 March · all expenses entered positive'}</p></div><button onClick={()=>setData(!data)}>{data?'Return to model':'View case data'}</button></div>
 {!data?<><div className="formula-bar"><span className="address">{active}</span><span className="fx">fx</span><input aria-label={'Formula for '+active} value={cells[active]||''} placeholder="Enter a number or an Excel-style formula" onChange={e=>change(active,e.target.value)} onKeyDown={e=>{if(e.key==='Enter')document.getElementById('cell-'+active)?.focus();}}/><button onClick={fill} title="Copy the selected formula across matching historical or forecast cells">Fill right →</button></div><p className="sheet-help">Green outline = this step · blue text = inputs · black text = formulas. Click a cell to edit; Tab moves right. Formula bar shows the stored formula.</p>
 <div className="grid-scroll"><Table className="model-grid"><TableHeader><TableRow><TableHead className="row-number">#</TableHead><TableHead className="row-label">A · Line item</TableHead>{grid.cols.map(c=><TableHead key={c}><b>{c}</b><span>{grid.cols.length===1?'Transaction / returns':years[columns.indexOf(c)]}</span></TableHead>)}</TableRow></TableHeader><TableBody>{grid.rows.map(r=><TableRow key={r} className={[11,13,17,38,39,40,41,50,53,54,62,69,70,71,77,78,81,82,83].includes(r)?'total':''}><TableCell className="row-number">{r}</TableCell><TableCell className="row-label">{labels[r]}</TableCell>{grid.cols.map(c=>{const ref=c+r,exists=ref in solution;return <TableCell key={ref} className={'value-cell '+(cellStep[ref]===step?'current ':'')+(checked&&cellStep[ref]===step&&errors[ref]?'incorrect ':'')+(active===ref?'selected ':'')}>{exists?<input id={'cell-'+ref} aria-label={ref+' '+labels[r]+' '+years[columns.indexOf(c)]} title={ref+(errors[ref]&&cells[ref]?' · '+errors[ref]:'')} className={solution[ref].startsWith('=')?'formula':'input-value'} value={active===ref&&editing?(cells[ref]||''):formatted(cells,ref)} placeholder={cellStep[ref]===step?'…':''} onFocus={()=>{setActive(ref);setEditing(true);}} onBlur={()=>setEditing(false)} onChange={e=>change(ref,e.target.value)} onPaste={e=>paste(e,ref)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();const next=grid.rows[grid.rows.indexOf(r)+1];if(next)document.getElementById('cell-'+c+next)?.focus();else e.currentTarget.blur();}}}/>:<span className="not-used">—</span>}</TableCell>;})}</TableRow>)}</TableBody></Table></div>
 <Tabs value={view} onValueChange={v=>{setView(v);setEditing(false);}} className="sheet-tabs"><TabsList aria-label="Model sections">{Object.entries(views).map(([k])=><TabsTrigger key={k} value={k}>{k==='A'?'Assumptions':k}</TabsTrigger>)}</TabsList></Tabs><p className="small">IS: income statement · TS: transaction summary · DS: debt schedule · CF: cash flow · RA: returns. Tabs display sections of one worksheet, so cell references stay simple.</p>
 </>:<div className="case-data"><h3>Historical income statement</h3><p>Copy these rows into the matching model cells. Exclude labels and year headings.</p><Table><TableHeader><TableRow><TableHead>Model row</TableHead>{years.slice(0,3).map(y=><TableHead key={y}>{y}</TableHead>)}<TableHead>Copy</TableHead></TableRow></TableHeader><TableBody>{historicalRows.map((r,i)=><TableRow key={r}><TableCell>{r} · {labels[r]}</TableCell>{historical[i].map((v,j)=><TableCell key={j}>{v}</TableCell>)}<TableCell><button onClick={()=>copy(historical[i].join('\t'))}>Copy → B{r}</button></TableCell></TableRow>)}</TableBody></Table><h3>Annual assumptions · E20:I28</h3><p>{rates.map((v,i)=>labels[20+i]+': '+v*100+'%').join(' · ')}</p><button onClick={()=>copy(rates.map(v=>Array(5).fill(v).join('\t')).join('\n'))}>Copy all forecast assumptions</button><h3>Transaction inputs</h3><div className="transaction-data">{[33,35,37,42,43,44,45,74].map(r=><p key={r}><b>B{r} · {labels[r]}</b><span>{solution['B'+r]}</span></p>)}</div><h3>Case conventions</h3><dl>{policies.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>}
 <div className="notice" role="status">{notice||'Work is saved in this browser. Download your work before switching devices.'}</div><div className="downloads"><button onClick={download}>↓ My model · CSV</button><a href="/CedarPack-Practice.xlsx" download>↓ Blank practice workbook</a><span>{assisted.length} cells revealed with help</span></div>
 {passed===12&&<div className="completion"><h2>Your first LBO is complete</h2><p>Base case: <b>{formatted(cells,'B70')} MOIC</b> and <b>{formatted(cells,'B71')} IRR</b>. At a 7.0x exit: <b>{formatted(cells,'B78')} IRR</b>.</p><p>Explain how earnings growth, debt repayment and cash accumulation create the equity gain. Your CSV retains cell addresses and formulas, but not app formatting.</p></div>}</section></div>
 <footer>Original teaching exercise based on the modelling sequence in Rosenbaum &amp; Pearl, Investment Banking, Chapter 5. Fictional data; simplified cash-flow LBO.<details><summary>Start a fresh attempt</summary><p>This clears the work saved in this browser. Download your model first.</p><button onClick={()=>{setCells({});setAssisted([]);go(0);setNotice('A fresh attempt is ready.');}}>Clear my model and restart</button></details></footer></main>
}
