import assert from 'node:assert/strict';
import {evaluate,solution,stepCells,lessons,checkCell,shiftFormula} from './model.mjs';
for(const ref of Object.keys(solution)){assert.equal(checkCell(solution,ref),null,ref);assert.ok(Number.isFinite(evaluate(solution,ref)),ref);}
assert.equal(lessons.reduce((s,x)=>s+x.minutes,0),120);
assert.equal(stepCells.flat().length,Object.keys(solution).length);
assert.equal(evaluate(solution,'B39'),204);assert.equal(evaluate(solution,'I50'),60);
assert.ok(Math.abs(evaluate(solution,'I53')-43.5077708288)<1e-9);
assert.ok(Math.abs(evaluate(solution,'B71')-.17334664374420838)<1e-12);
for(const r of ['B81','B82','B83'])assert.equal(evaluate(solution,r),0);
for(const c of ['E','F','G','H','I'])assert.equal(evaluate(solution,c+'54'),0);
assert.equal(checkCell({...solution,B14:''},'B14'),'Missing entry');
assert.match(checkCell({...solution,B71:'17.334664'},'B71'),/formula/);
assert.match(checkCell({...solution,B71:'=B71'},'B71'),/Circular/);
assert.throws(()=>evaluate({A1:'=1/0'},'A1'),/Division/);
assert.throws(()=>evaluate({A1:'=fetch("x")'},'A1'),/Unsupported/);
assert.equal(evaluate({A1:'8%'},'A1'),.08);
assert.equal(shiftFormula('=MIN(E46,$B$36*E28)',3),'=MIN(H46,$B$36*H28)');
const later={...solution,I20:'.04'};assert.equal(evaluate(later,'H7'),evaluate(solution,'H7'));assert.ok(evaluate(later,'I7')<evaluate(solution,'I7'));assert.ok(evaluate(later,'B71')<evaluate(solution,'B71'));
const overpaid={...solution,E28:'2'};assert.equal(evaluate(overpaid,'E49'),120);assert.equal(evaluate(overpaid,'E50'),0);assert.ok(evaluate(overpaid,'E54')>0);
const lowProfit={...solution,E22:'.9'};assert.equal(evaluate(lowProfit,'E16'),0);assert.ok(evaluate(lowProfit,'E54')>0);
const noDebt={...solution,B35:'0'};assert.equal(evaluate(noDebt,'I50'),0);assert.equal(evaluate(noDebt,'E47'),0);
assert.ok(evaluate({...solution,B42:'7'},'B71')<evaluate(solution,'B71'));
console.log('Model tests passed: complete solution, 120-minute lessons, reconciliations, rates, fill-right, later-year drivers, zero debt, tax losses, repayment cap, and funding deficits.');
