export const columns=['B','C','D','E','F','G','H','I'];
export const years=['FY2024A','FY2025A','FY2026A','FY2027E','FY2028E','FY2029E','FY2030E','FY2031E'];
export const labels={7:'Revenue',8:'Cost of goods sold',9:'Gross profit',10:'Operating expenses (excluding D&A)',11:'EBITDA',12:'Depreciation & amortization',13:'EBIT',14:'Interest expense',15:'Earnings before tax',16:'Cash taxes',17:'Net income',20:'Revenue growth',21:'COGS / revenue',22:'Operating expenses / revenue',23:'D&A / revenue',24:'Capital expenditure / revenue',25:'Net working capital / revenue',26:'Cash tax rate',27:'Loan interest rate',28:'Amortization / original principal',32:'Entry EBITDA',33:'Entry EV / EBITDA',34:'Purchase enterprise value',35:'Debt / entry EBITDA',36:'New term loan',37:'One-time transaction fees',38:'Total uses',39:'Sponsor equity investment',40:'Total sources',41:'Sources less uses',42:'Exit EV / EBITDA',43:'Holding period (years)',44:'Opening net working capital',45:'Opening cash',46:'Beginning debt',47:'Interest on beginning debt',48:'Cash available before principal repayment',49:'Scheduled principal repayment',50:'Ending debt',51:'Cash after principal repayment',52:'Beginning cash',53:'Ending cash',54:'Unfunded cash shortfall',57:'Net income',58:'Add back D&A',59:'Capital expenditure',60:'Net working capital',61:'Increase in net working capital',62:'Cash available before principal repayment',65:'Exit EBITDA',66:'Exit enterprise value',67:'Less: exit debt',68:'Add: exit cash',69:'Sponsor exit equity proceeds',70:'Multiple of invested capital (MOIC)',71:'Annualized equity return (IRR)',74:'Downside exit EV / EBITDA',75:'Downside exit enterprise value',76:'Downside equity proceeds',77:'Downside MOIC',78:'Downside IRR',81:'Sources less uses (target zero)',82:'Debt roll-forward difference (target zero)',83:'Cash roll-forward difference (target zero)',84:'Minimum year-end cash (must be nonnegative)',85:'Year 1 EBITDA / interest'};
export const historicalRows=[7,8,10,12,14,16];
export const historical=[[160,180,200],[96,108,120],[32,36,40],[4.5,5,6],[0,0,0],[6.875,7.75,8.5]];
export const rates=[.08,.6,.2,.03,.04,.1,.25,.1,.1];
export const policies=[['Close date','31 March 2026, after FY2026 results'],['Exit date','31 March 2031, after year-end cash flow and debt repayment'],['Business','CedarPack Industries, a fictional cardboard packaging manufacturer'],['Units','All amounts in INR crore. All expenses and outflows entered as positive numbers.'],['Purchase','Debt-free, cash-free acquisition. No existing debt is refinanced.'],['Fees','INR 4 crore paid at closing and funded in uses; no tax deduction or amortization.'],['Loan','One term loan. Interest is 10% of beginning-of-year debt, paid at year end.'],['Principal','10% of original loan principal repaid each year, capped at beginning debt. Balloon repaid at exit.'],['Surplus cash','No cash sweep or dividends. Cash earns no interest and accumulates until exit.'],['Opening position','NWC of INR 20 crore is included in the acquired business. Opening cash is zero.'],['Depreciation','Total depreciation and amortization assumed at 3% of revenue. No detailed fixed asset schedule.'],['Taxes','25% of positive EBT. No tax refunds, loss carryforwards, or interest deductibility limits. This is a teaching assumption.'],['Simplifications','No revolver, PIK, multiple debt tranches, goodwill, purchase accounting, full balance sheet, or exit fees.'],['Cash deficit','Negative cash means additional funding is required. This case provides no automatic funding plug.'],['Source','All company data and assumptions are invented for this exercise.'],['Method','Adapted in original wording from the five-stage workflow in Rosenbaum & Pearl, Investment Banking, Chapter 5.']];
export const solution={};export const cellStep={};
function put(ref,value,step){solution[ref]=String(value);cellStep[ref]=step;}
historicalRows.forEach((r,i)=>['B','C','D'].forEach((c,j)=>put(c+r,historical[i][j],0)));
for(const c of ['B','C','D'])for(const [r,f]of [[9,`=${c}7-${c}8`],[11,`=${c}9-${c}10`],[13,`=${c}11-${c}12`],[15,`=${c}13-${c}14`],[17,`=${c}15-${c}16`]])put(c+r,f,1);
for(const c of ['E','F','G','H','I'])rates.forEach((x,i)=>put(c+(20+i),x,2));
for(const c of ['E','F','G','H','I']){const p=String.fromCharCode(c.charCodeAt(0)-1);for(const [r,f]of [[7,`=${p}7*(1+${c}20)`],[8,`=${c}7*${c}21`],[9,`=${c}7-${c}8`],[10,`=${c}7*${c}22`],[11,`=${c}9-${c}10`],[12,`=${c}7*${c}23`],[13,`=${c}11-${c}12`]])put(c+r,f,3);}
for(const [r,v]of [[32,'=D11'],[33,8],[34,'=B32*B33'],[35,3],[36,'=B32*B35'],[37,4],[38,'=B34+B37'],[39,'=B38-B36'],[40,'=B36+B39'],[41,'=B40-B38'],[42,8],[43,5],[44,20],[45,0]])put('B'+r,v,4);
for(const c of ['E','F','G','H','I']){const p=String.fromCharCode(c.charCodeAt(0)-1);for(const[r,f]of [[46,c==='E'?'=$B$36':`=${p}50`],[47,`=${c}46*${c}27`],[49,`=MIN(${c}46,$B$36*${c}28)`],[50,`=${c}46-${c}49`],[14,`=${c}47`]])put(c+r,f,5);for(const[r,f]of [[15,`=${c}13-${c}14`],[16,`=MAX(${c}15,0)*${c}26`],[17,`=${c}15-${c}16`]])put(c+r,f,6);for(const[r,f]of [[57,`=${c}17`],[58,`=${c}12`],[59,`=${c}7*${c}24`],[60,`=${c}7*${c}25`],[61,`=${c}60-${p}60`],[62,`=${c}57+${c}58-${c}59-${c}61`]])put(c+r,f,7);for(const[r,f]of [[48,`=${c}62`],[51,`=${c}48-${c}49`],[52,c==='E'?'=$B$45':`=${p}53`],[53,`=${c}52+${c}51`],[54,`=MAX(0,-${c}53)`]])put(c+r,f,8);}
put('D60','=$B$44',7);
for(const[r,f]of [[65,'=I11'],[66,'=B65*B42'],[67,'=I50'],[68,'=I53'],[69,'=B66-B67+B68'],[70,'=B69/B39'],[71,'=B70^(1/B43)-1']])put('B'+r,f,9);
for(const[r,f]of [[74,7],[75,'=B65*B74'],[76,'=B75-B67+B68'],[77,'=B76/B39'],[78,'=B77^(1/B43)-1']])put('B'+r,f,10);
for(const[r,f]of [[81,'=B41'],[82,'=B36-SUM(E49:I49)-I50'],[83,'=B45+SUM(E51:I51)-I53'],[84,'=MIN(E53:I53)'],[85,'=E11/E47']])put('B'+r,f,11);
export const views={IS:{title:'Income statement',rows:[7,8,9,10,11,12,13,14,15,16,17],cols:columns},A:{title:'Operating assumptions',rows:[20,21,22,23,24,25,26,27,28],cols:['E','F','G','H','I']},TS:{title:'Transaction summary',rows:[32,33,34,35,36,37,38,39,40,41,42,43,44,45],cols:['B']},DS:{title:'Debt & cash schedule',rows:[46,47,48,49,50,51,52,53,54],cols:['E','F','G','H','I']},CF:{title:'Cash flow',rows:[57,58,59,60,61,62],cols:['D','E','F','G','H','I']},RA:{title:'Investor returns',rows:[65,66,67,68,69,70,71,74,75,76,77,78,81,82,83,84,85],cols:['B']}};
export const lessons=[
{title:'Collect historical data',book:'I · Locate and analyze information',minutes:10,view:'IS',why:'Before forecasting a buyout, establish what the business earns. CedarPack sells packaging to consumer goods companies. Its financial year ends on 31 March.',task:'Download the data workbook. Open Historical. Copy B7:D8 into B7:D8 here, then copy B10:D10, B12:D12, B14:D14 and B16:D16 into their matching rows. Paste values only; keep all expenses positive.',hint:'Select the top-left highlighted cell before pasting from Excel. Zero interest is a real input, not an empty cell. You can also use the Case data tab to copy each row.',example:'B7 = 160; C7 = 180; D7 = 200',question:'Why should historical interest be zero?',answer:'The fictional company has no debt before acquisition. The buyout introduces new debt.'},
{title:'Build historical earnings',book:'II · Build the pre-LBO model',minutes:10,view:'IS',why:'EBITDA measures earnings before interest, tax, depreciation and amortization. EBIT subtracts depreciation and amortization. Neither equals cash flow.',task:'Calculate rows 9, 11, 13, 15 and 17 for B:D. Start with B9 = B7 − B8. Write formulas beginning with =. Select a formula cell and use Fill right to copy across the historical years.',hint:'Gross profit = revenue − COGS. EBITDA = gross profit − operating expenses. EBIT = EBITDA − D&A. EBT = EBIT − interest. Net income = EBT − taxes.',example:'=B7-B8',question:'Why subtract D&A to get EBIT?',answer:'D&A allocates the cost of long-lived assets to accounting periods, so it reduces operating accounting profit.'},
{title:'Enter the forecast assumptions',book:'II · Build the pre-LBO model',minutes:10,view:'A',why:'Forecasts should be driven by explicit assumptions. Each year has its own input so a later-year assumption can change without rewriting a formula.',task:'In the data workbook, open Assumptions and copy E20:I28 into E20:I28 here. The rows are growth, COGS, operating expenses, D&A, capex, NWC, taxes, interest, and loan amortization.',hint:'Enter 8% or 0.08 for growth, not 8. The annual defaults are 8%, 60%, 20%, 3%, 4%, 10%, 25%, 10%, 10%. Loan amortization means principal repayment; it is different from accounting D&A.',example:'E20 = 8%',question:'What does NWC of 10% of revenue mean?',answer:'The business ties up 10% of annual sales in operating working capital, net of operating current liabilities. Growth requires additional cash.'},
{title:'Project revenue through EBIT',book:'II · Build the pre-LBO model',minutes:15,view:'IS',why:'Start with the operating business before adding the acquisition financing. Growth increases sales while constant cost ratios keep EBITDA margin at 20%.',task:'Build E7:E13, then fill each row right through I. Revenue = prior-year revenue × (1 + growth). Use the matching year’s COGS, operating expense and D&A ratios.',hint:'Use E7=D7*(1+E20), E8=E7*E21, E9=E7-E8, E10=E7*E22, E11=E9-E10, E12=E7*E23 and E13=E11-E12.',example:'=D7*(1+E20)',question:'Why are capex and D&A different?',answer:'Capex is current cash spending. D&A is an accounting expense. This exercise assumes capex at 4% and D&A at 3% of sales.'},
{title:'Price and finance the acquisition',book:'III · Input transaction structure',minutes:10,view:'TS',why:'Uses describe what must be paid at closing. Sources describe who provides the money. Sponsor equity funds the amount not covered by the new term loan.',task:'Use Transaction in the data workbook for the blue input cells. Link entry EBITDA to D11. Calculate enterprise value, debt, uses, sponsor equity, sources and the zero-difference check. Fees are part of uses.',hint:'EV = entry EBITDA × 8.0x. Debt = entry EBITDA × 3.0x. Uses = EV + fees. Sponsor equity = uses − debt. This is a debt-free, cash-free purchase, so seller proceeds equal EV.',example:'=B32*B33',question:'Why does the sponsor fund more than EV minus debt?',answer:'The sponsor also funds INR 4 crore of transaction fees. Fees increase the investment but do not increase enterprise value.'},
{title:'Schedule the loan and interest',book:'IV · Complete the post-LBO model',minutes:10,view:'DS',why:'Beginning-balance interest avoids circular formulas. Scheduled amortization is 10% of original principal each year, not 10% of the remaining balance.',task:'Calculate rows 46, 47, 49 and 50 for E:I. E46 links to $B$36; later beginning balances link to the previous ending debt. Then open IS and link E14:I14 to interest in row 47.',hint:'Interest = beginning debt × interest rate. Repayment = MIN(beginning debt, original loan × annual amortization rate). Ending debt = beginning debt − repayment. Dollar signs keep original principal fixed when filling right.',example:'=MIN(E46,$B$36*E28)',question:'Why use MIN for principal repayment?',answer:'It prevents the scheduled payment from exceeding outstanding debt. Any remaining balance is repaid when the company is sold.'},
{title:'Finish the post-buyout income statement',book:'IV · Complete the post-LBO model',minutes:10,view:'IS',why:'The new loan creates interest expense, which lowers earnings before tax and the assumed cash tax bill.',task:'Calculate E15:I17. Subtract interest from EBIT. Taxes equal 25% of positive EBT; use MAX to avoid a tax refund on losses. Net income is EBT less cash taxes.',hint:'E15=E13-E14. E16=MAX(E15,0)*E26. E17=E15-E16. This lesson assumes accounting tax expense equals cash taxes.',example:'=MAX(E15,0)*E26',question:'Does loan principal repayment reduce net income?',answer:'No. Interest is an expense; principal repayment is a financing cash outflow.'},
{title:'Convert earnings into cash',book:'IV · Complete the post-LBO model',minutes:15,view:'CF',why:'Net income includes noncash D&A and excludes capex and working capital investment. We adjust for these to find cash available before principal repayment.',task:'Link D60 to $B$44 for opening NWC. In E:I, link net income and D&A, calculate capex and NWC from revenue, calculate the change in NWC, and finish row 62.',hint:'Cash available = net income + D&A − capex − increase in NWC. E61=E60-D60. Deduct the change in NWC, not the entire NWC balance. Interest is already included in net income.',example:'=E57+E58-E59-E61',question:'Why add D&A back?',answer:'It reduced net income without using current-period cash. Capex is the separate cash investment in assets.'},
{title:'Track cash and funding needs',book:'IV · Complete the post-LBO model',minutes:10,view:'DS',why:'Debt payments consume cash. With no cash sweep, remaining cash stays in the company and increases equity proceeds at exit.',task:'Complete rows 48 and 51:54 for E:I. Link cash available to row 62. Subtract scheduled principal repayment, then roll cash forward. Beginning cash in E52 links to $B$45.',hint:'Ending cash = beginning cash + cash after repayment. Shortfall = MAX(0,−ending cash). A positive shortfall means the case needs extra funding; never silently plug a revolver.',example:'=E52+E51',question:'Can a company show a profit and still need funding?',answer:'Yes. Capex, working capital and principal repayment can consume more cash than earnings generate.'},
{title:'Calculate sponsor returns',book:'V · Perform the LBO analysis',minutes:10,view:'RA',why:'Sell the business at 8.0x year-five EBITDA. Repay remaining debt and distribute accumulated cash to the sponsor.',task:'Calculate B65:B71. Exit EV = year-five EBITDA × exit multiple. Equity proceeds = exit EV − debt + cash. MOIC = proceeds / initial sponsor equity. Annualized return = MOIC^(1/5) − 1.',hint:'The annualized return equals IRR here because there is only one investment at closing and one receipt exactly five years later. There are no interim sponsor dividends.',example:'=B70^(1/B43)-1',question:'Why add cash to enterprise value?',answer:'Enterprise value prices the operating business. Cash is an additional asset available to equity holders after paying debt.'},
{title:'Test a lower exit multiple',book:'V · Perform the LBO analysis',minutes:5,view:'RA',why:'A buyout should not rely on selling at a higher multiple. A lower exit multiple can reduce returns even when earnings grow and debt declines.',task:'Enter 7.0 in B74. Calculate B75:B78 using the same year-five EBITDA, debt, cash and initial equity. Compare downside IRR with the base-case IRR.',hint:'Only the exit multiple changes in this comparison. B75=B65*B74. B76=B75-B67+B68. B77=B76/B39. B78=B77^(1/B43)-1.',example:'=B65*B74',question:'Which three things explain the base-case equity gain?',answer:'EBITDA growth at a constant multiple, debt repayment, and cash accumulation. Entry fees reduce net investment returns.'},
{title:'Reconcile and explain the deal',book:'V · Perform the LBO analysis',minutes:5,view:'RA',why:'A model is useful only if its flows reconcile and the financing is feasible. Finish by explaining where the return comes from.',task:'Calculate B81:B85. Sources less uses, the debt roll-forward difference and the cash roll-forward difference must be zero. Minimum year-end cash must be nonnegative. Interpret year-one EBITDA / interest.',hint:'Debt difference = initial debt − total principal repayments − final debt. Cash difference = opening cash + total cash after repayment − final cash. EBITDA / interest is a simple coverage ratio, not a full debt-service test.',example:'=B36-SUM(E49:I49)-I50',question:'What should your final recommendation acknowledge?',answer:'This fictional base case funds its scheduled debt payments. Returns depend on forecast growth and exit pricing. A real investment requires business diligence, downside funding analysis and more detailed modelling.'}
];
export const stepCells=lessons.map((_,i)=>Object.keys(cellStep).filter(c=>cellStep[c]===i));
export function evaluate(cells,ref,stack=new Set()){
 ref=ref.replace(/\$/g,'').toUpperCase();if(stack.has(ref))throw Error('Circular reference at '+ref);const raw=String(cells[ref]??'').trim();if(!raw)throw Error('Missing '+ref);if(!raw.startsWith('=')){const n=Number(raw.replace(/,/g,'').replace(/%$/,''))/(raw.endsWith('%')?100:1);if(!Number.isFinite(n))throw Error('Enter a number or formula in '+ref);return n;}
 const next=new Set(stack);next.add(ref);const src=raw.slice(1).toUpperCase().replace(/\$/g,'').replace(/\s/g,'');const toks=src.match(/\d*\.?\d+(?:E[+-]?\d+)?|[A-Z]+[0-9]+|[A-Z]+|[()+\-*/^%,:]/g)||[];if(toks.join('')!==src)throw Error('Unsupported formula syntax');let pos=0;
 const take=()=>toks[pos++];const need=x=>{if(take()!==x)throw Error('Expected '+x);};
 function primary(){let t=take(),n;if(t==='('){n=expr();need(')');}else if(/^\d*\.?\d+(E[+-]?\d+)?$/.test(t??'')){n=Number(t);}else if(/^[A-Z]+\d+$/.test(t??'')){n=evaluate(cells,t,next);}else if(['SUM','MIN','MAX'].includes(t)){need('(');const args=[];do{if(toks[pos+1]===':'){const a=take();take();const b=take();const am=a.match(/^([A-Z])(\d+)$/),bm=b?.match(/^([A-Z])(\d+)$/);if(!am||!bm||am[1]>bm[1]||+am[2]>+bm[2])throw Error('Invalid range');for(let r=+am[2];r<=+bm[2];r++)for(let c=am[1].charCodeAt(0);c<=bm[1].charCodeAt(0);c++)args.push(evaluate(cells,String.fromCharCode(c)+r,next));}else args.push(expr());if(toks[pos]!==',')break;take();}while(true);need(')');n=t==='SUM'?args.reduce((a,b)=>a+b,0):t==='MIN'?Math.min(...args):Math.max(...args);}else throw Error('Use references, arithmetic, SUM, MIN or MAX');while(toks[pos]==='%'){take();n/=100;}return n;}
 function unary(){if(toks[pos]==='-'){take();return-unary();}if(toks[pos]==='+'){take();return unary();}return primary();}function power(){let n=unary();while(toks[pos]==='^'){take();n=n**unary();}return n;}function term(){let n=power();while(['*','/'].includes(toks[pos])){const op=take(),v=power();if(op==='/'&&v===0)throw Error('Division by zero');n=op==='*'?n*v:n/v;}return n;}function expr(){let n=term();while(['+','-'].includes(toks[pos])){const op=take(),v=term();n=op==='+'?n+v:n-v;}return n;}const result=expr();if(pos!==toks.length||!Number.isFinite(result))throw Error('Invalid formula');return result;
}
export function checkCell(cells,ref){if(!String(cells[ref]??'').trim())return'Missing entry';try{const value=evaluate(cells,ref);const expected=evaluate(solution,ref);if(solution[ref].startsWith('=')&&(!String(cells[ref]).startsWith('=')||!/[A-Z]\$?\d/i.test(cells[ref])))return'Use a formula with cell references';const tol=isPercent(ref)?0.00005:0.005;if(Math.abs(value-expected)>tol)return'Check your calculation or source data';return null;}catch(e){return e.message;}}
export function isPercent(ref){const r=Number(ref.replace(/\D/g,''));return(r>=20&&r<=28)||r===71||r===78;}
export function formatted(cells,ref){try{const v=evaluate(cells,ref);if(isPercent(ref))return(v*100).toFixed(2)+'%';if([33,35,42,70,74,77,85].includes(Number(ref.slice(1))))return v.toFixed(2)+'x';return v.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});}catch{return String(cells[ref]??'').trim()?'⚠':'';}}
export function shiftFormula(formula,delta){return formula.replace(/(\$?)([A-Z]+)(\$?\d+)/g,(m,abs,c,row)=>{if(abs)return m;let n=0;for(const ch of c)n=n*26+ch.charCodeAt(0)-64;n+=delta;if(n<1)throw Error('Reference outside sheet');let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s+row;});}

